 personajes.add(new Personaje("Kratos", "Masculino", "Ficticio", "Videojuegos", null, "Play Station", null, null));
        personajes.add(new Personaje("El Penitente", "Masculino", "Ficticio", "Videojuegos", null, "Play Station", null, null));
        personajes.add(new Personaje("Calamardo", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Caricaturas"));
        personajes.add(new Personaje("Lucifugio", "Masculino", "Ficticio", "Mitología", null, null, null, null));
        personajes.add(new Personaje("Da Vinci", "Masculino", "Real", "Artista", null, null, "Pintor", null));
        personajes.add(new Personaje("Beelzeebub", "Masculino", "Ficticio", "Mitología", null, null, null, null));
        personajes.add(new Personaje("Batman", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Superhéroe"));
        personajes.add(new Personaje("Cristiano Ronaldo", "Masculino", "Real", "Deportes", "Futbol", null, null, null));
        personajes.add(new Personaje("Wanda", "Femenino", "Ficticio", "Series y Peliculas", null, null, null, "Superhéroes"));
        personajes.add(new Personaje("Leon S. Kennedy", "Masculino", "Ficticio", "Videojuegos", null, "Play Station", null, null));
        personajes.add(new Personaje("Gohan", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Anime"));
        personajes.add(new Personaje("Karely Ruiz", "Femenino", "Real", "Artista", null, null, "Cantante", null));
        personajes.add(new Personaje("Dr. Simmi", "Masculino", "Real", "Marca", null, "Farmacia", null, null));
        personajes.add(new Personaje("El Tigre Toño", "Masculino", "Ficticio", "Marca", null, "Comida", null, null));
        personajes.add(new Personaje("Triple H", "Masculino", "Real", "Series y Peliculas", null, null, null, "Luchador"));
        personajes.add(new Personaje("Miguel Coco", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Animación"));
        personajes.add(new Personaje("Yoshi", "Masculino", "Ficticio", "Videojuegos", null, "Nintendo", null, null));
        personajes.add(new Personaje("Michael Jackson", "Masculino", "Real", "Artista", null, null, "Cantante", null));
        personajes.add(new Personaje("Fredie Mercury", "Masculino", "Real", "Artista", null, null, "Cantante", null));
        personajes.add(new Personaje("Chicharito", "Masculino", "Real", "Deportes", "Futbol", null, null, null));
        personajes.add(new Personaje("Checo Perez", "Masculino", "Real", "Deportes", "Carreras", null, null, null));
        personajes.add(new Personaje("Spiderman", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Superhéroe"));
        personajes.add(new Personaje("Juan Escutia", "Masculino", "Real", "Historia", null, null, null, null));
        personajes.add(new Personaje("Mama Coco", "Femenino", "Ficticio", "Series y Peliculas", null, null, null, "Animación"));
        personajes.add(new Personaje("Luis Miguel", "Masculino", "Real", "Artista", null, null, "Cantante", null));
        personajes.add(new Personaje("Wario", "Masculino", "Ficticio", "Videojuegos", null, "Nintendo", null, null));
        personajes.add(new Personaje("Seita", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Anime"));
        personajes.add(new Personaje("Mulan", "Femenino", "Ficticio", "Series y Peliculas", null, null, null, "Animación"));
        personajes.add(new Personaje("Andy", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Animación"));
        personajes.add(new Personaje("La Mole", "Masculino", "Real", "Artista", null, null, "Comediante", null));
        personajes.add(new Personaje("Dr. Strange", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Superhéroe"));
        personajes.add(new Personaje("Patricio Estrella", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Caricaturas"));
        personajes.add(new Personaje("Come Galletas", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Caricaturas"));
        personajes.add(new Personaje("Etzio", "Masculino", "Ficticio", "Videojuegos", null, "Play Station", null, null));
        personajes.add(new Personaje("Junior H", "Masculino", "Real", "Artista", null, null, "Cantante", null));
        personajes.add(new Personaje("Sonic", "Masculino", "Ficticio", "Videojuegos", null, "Sega", null, null));
        personajes.add(new Personaje("Naruto", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Anime"));
        personajes.add(new Personaje("Cosmo", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Caricaturas"));
        personajes.add(new Personaje("Bambi", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Animación"));
        personajes.add(new Personaje("Lucy", "Femenino", "Ficticio", "Series y Peliculas", null, null, null, "Caricaturas"));
        personajes.add(new Personaje("Dinosaurio de Google", "Masculino", "Ficticio", "Videojuegos", null, "Google", null, null));
        personajes.add(new Personaje("Cheems", "Masculino", "Real", "Artista", null, null, "Meme", null));
        personajes.add(new Personaje("Franco Escamilla", "Masculino", "Real", "Artista", null, null, "Comediante", null));
        personajes.add(new Personaje("Luffy", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Anime"));
        personajes.add(new Personaje("Mr. Beats", "Masculino", "Real", "Artista", null, null, "Productor", null));
        personajes.add(new Personaje("AMLO", "Masculino", "Real", "Artista", null, null, "Meme", null));
        personajes.add(new Personaje("Mario", "Masculino", "Ficticio", "Videojuegos", null, "Nintendo", null, null));
        personajes.add(new Personaje("Napoleon", "Masculino", "Real", "Historia", null, null, null, null));
        personajes.add(new Personaje("Hittler", "Masculino", "Real", "Historia", null, null, null, null));
        personajes.add(new Personaje("Goku", "Masculino", "Ficticio", "Series y Peliculas", null, null, null, "Anime"));
        personajes.add(new Personaje("Leonel Messi", "Masculino", "Real", "Deportes", "Futbol", null, null, null));        


        TIPO DE ENTRETENIMIENTO Y TIPO DE ARTISTA